---
- name: Install nginx and prometheus charts
  gather_facts: No
  hosts: all

  tasks:
#   - name: Add prometheus-community chart repo
#     community.kubernetes.helm_repository:
#       name: prometheus-community
#       repo_url: "https://prometheus-community.github.io/helm-charts"

#   - name: Deploy latest version of Prometheus chart
#     community.kubernetes.helm:
#       name: my-prometheus
#       chart_ref: prometheus-community/kube-prometheus-stack
#       release_namespace: default

#   - name: Verify that the application does not exist
#     community.kubernetes.helm:
#       name: my-release
#       chart_ref: bitnami/nginx
#       release_namespace: default
#       state: absent

   - name: Deploy nginx with static site
     community.kubernetes.helm:
       name: my-release
       chart_ref: bitnami/nginx
       release_namespace: default
       values: "{{ lookup('template', 'values.yaml') | from_yaml }}"

