image:
  registry: rafa73
  repository: static_site
  tag: latest              # {{ my_tag }}

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 10s         # Interval at which metrics should be scraped
    selector:
      release: my-prometheus

